#!/bin/sh
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR $against | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "执行语法检测..."
for FILE in $SFILES
do
    php -l -d display_errors=0 $FILE
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $FILE"
done

if [ "$FILES" != "" ]
then
    echo "执行代码规范检测..."
    ./vendor/bin/phpcs --standard=./vendor/wide/code_standard/ruleset.xml --report=summary --encoding=utf-8 $FILES
    if [ $? != 0 ]
    then
        echo "自动修复部分错误..."
        ./vendor/bin/phpcbf --standard=./vendor/wide/code_standard/ruleset.xml --encoding=utf-8 $FILES
        echo "部分错误不能自动修复需要手动修复, 查看详细错误信息，可执行以下命令："
        echo "./vendor/bin/phpcs --standard=./vendor/wide/code_standard/ruleset.xml --report=full --encoding=utf-8 file\n"
        exit 1
    fi
fi